### ISSUE TITLE
Can't install json-proxy when using Nexus NPM

### ISSUE THREAD

**Issue by jgiovaresco** [steve-jansen/json-proxy#25]
With last versions of json-proxy, we can't install _json-proxy_ with a Nexus NPM.

I think the problem comes from the **resolved** attribute in each dependency of **npm-shrinkwrap.json** file. Dependencies are retrieved  using the url defined in **resolved** attribute instead of using our Nexus url.

**Comment by steve-jansen** [comment]
Hi @jgiovaresco 

This is a good one!   This is an open issue - see npm/npm#3581 .  I'm not sure what the best fix is.  I can obviously remove the shrinkwrap file.  That fixes your issue, but, could cause new problems for other users with breaking changes introduced by other modules.

The temporary workaround for your situation appears to be:

```
npm install --no-shrinkwrap
```

Let me know if that's good enough for you until npm can upgrade shrinkwrap `resolved` fields to use checksums instead of absolute URLs.

Cheers,
Steve

**Comment by jgiovaresco** [comment]
Thanks for the workaround. It's better than mine which was to downgrade json-proxy...

**Comment by steve-jansen** [comment]
Closing since there's a reasonable workaround with `npm install --no-shrinkwrap`
